name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    name: OTP ${{matrix.otp}}
    strategy:
      matrix:
        otp: ['28', '27', '26']
        rebar3: ['3.25.0']
    runs-on: 'ubuntu-24.04'
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ matrix.otp }}
          rebar3-version: ${{ matrix.rebar3 }}
      - run: rebar3 as test compile
      - run: rebar3 ct
      - run: rebar3 ex_doc
        if: ${{ matrix.otp == '28' }}
      - run: rebar3 dialyzer
        if: ${{ matrix.otp == '28' }}
      - run: rebar3 as test codecov analyze
      - uses: codecov/codecov-action@v5
        with:
          name: Upload coverage reports to Codecov
          token: ${{ secrets.CODECOV_TOKEN }}
